#' Significance colour ramps
#'
#' Creates a colour ramp function based on one of the predefined
#' Significance colour palettes. The returned function can be used to
#' generate any number of interpolated colours and is particularly useful
#' for continuous colour scales in ggplot2.
#'
#' Available palettes are identical to those supported by [palette_sig()].
#'
#' @param palette Name of the base palette. See [palette_sig()] for the
#'   available options.
#' @param reverse Logical; if `TRUE`, reverse the colour order before
#'   creating the colour ramp.
#' @param random Logical; if `TRUE`, randomly shuffle the colours before
#'   creating the colour ramp.
#' @param n Number of colours to extract from the base palette before
#'   constructing the colour ramp. Defaults to `0`, which uses all colours
#'   in the selected palette.
#' @param ... Additional arguments passed to [grDevices::colorRampPalette()].
#'
#' @return
#' A function generated by [grDevices::colorRampPalette()] that returns a
#' vector of colour hex codes when called with the desired number of colours.
#'
#' @examples
#' library(ggplot2)
#'
#' ggplot(mtcars, aes(wt, mpg, colour = hp)) +
#'   geom_point(size = 3) +
#'   scale_colour_gradientn(
#'     colours = colorramp_sig("mintoplus")(100)
#'   ) +
#'   labs(
#'     colour = "Horsepower",
#'     x = "Weight",
#'     y = "Miles per gallon"
#'   )
#'
#' @keywords colour palette
#'
#' @export
colorramp_sig <- function(palette = "all", reverse = FALSE, random = FALSE, n = 0, ...) {

  #Structure of functions adapted from: https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2

  pal <- palette_sig(palette, n)

  if (reverse) pal <- rev(pal)
  if (random) pal <- sample(pal)

  colorRampPalette(pal, ...)
}
